### ISSUE TITLE
Mapper Refactor

### ISSUE THREAD

**Issue by purehyperbole** [ernestio/ernest#253]
Our current mapper services have become increasingly complicated with a large amount of duplicated and unclear functionality that needs to be implemented.

The mapping of each provider should be moved to a single library, with each provider mapping and components exposing a shared interface that can be used to:

- convert a definition to internal state
- convert internal state to a definition
- build internal state needed for querying provider for import

# Libmapper Library (32pt)

Handles the conversion:
- provider specific yaml document to generic graph format (graph lib)
- generic graph format (graph lib) to provider specific yaml document

Exposes a generic interface for all provider mappers to use. Provider components are defined here and satisfy the component interface defined by graph (graph library)

- [x] Add base aws definition (vpcs, subnets, instances, security_groups)
- [x] Add base aws components  (vpcs, subnets, instances, security_groups)
- [x] Map base aws components  (vpcs, subnets, instances, security_groups)
- [x] Define interface for components
- [x] Define interface for mapper
- [x] Support import queries
- [x] Changed how vpc's are defined on yaml, now optional and multiple can be specified.
- [x] Removed service prefix for component names, allowing more flexible importing
- [x] [3] Add remaining aws definition (nat_gateways, elb, ebs, s3, route_53, rds_instance)    
- [x] [8] Add remaining aws components (nat_gateways, elb, ebs, s3, route_53, rds_instance)
- [x] [5] Add remaining aws mappings (nat_gateways, elb, ebs, s3, route_53, rds_instance)
- [ ] [8] Port unit tests to aws components
- [x] [5-8?] Run integration tests against new (requires fixes for removal of service prefix)
- [x] [3] Handling of credentials

# Mapper Service (16pt)

Formerly definition-mapper, aws-definition-mapper, vcloud-definition-mapper.
Provides a nat interface to libmapper functionality. 

- [x] [5] [Nats handler, service.create, service.delete, service.patch (?) service.import](https://github.com/ernestio/ernest/issues/273)
- [x] [3] [Load/Save service from service-store](https://github.com/ernestio/ernest/issues/275)
- [x] [3] [Accept a service payload](https://github.com/ernestio/ernest/issues/276)

# Service store

- [x] [5] [responds to service.*.done](https://github.com/ernestio/ernest/issues/274)

# Graph Library (3pt)

A library for working with DAG's. This serves as the output format used by libmapper and scheduler. 
It provides functionality to resolve dependencies of generic components and build a graph based on this. 
It also supports a diff of two graphs, creating a set of changed components. This diff constructs the order in which these changes should occur (this diff serves the basis of the work that will be scheduled by the scheduler service).

- [x] Support for generic coponents
- [x] Diff two generic graphs to build a list of actionable changes
- [x] Support handling of sequential updates on components that are grouped
- [x] Graphviz output for debugging diff's and giving an overview of the 
- [x] Unit tests - basic
- [ ] [3] Unit tests for diffing service

# Scheduler Service

Accepts a directed graph and schedules components for create/update/delete/find based on the dependencies generated by libmapper and the graph library. Unlike workflow-mananger, components are sent individually and not in a group. This allows in the future for users to be able to specify their own dependencies/order of how things should be provisioned.

- [x] Core scheduler functionality - support for scheduling work units based on graph, handling errored components + unit tests
- [x] Expose nats endpoints
- [x] Load/Save service to/from service-store
- [x] Port over templating code

# Service-Store Service
- [x] Implement Gorm transactions of service operations 

# AWS Connector Library
- [x] Add additional fields to events

# CLI
- [x] Update CLI to support output of singular components rather than components.* and components.*.done

**Comment by adriacidre** [comment]
@purehyperbole as we're refactoring the way mappers behave, we should port vcloud mapper so we don't maintain 2 different workflows, shall we add it to the todo list?
